#https://docs.travis-ci.com/user/reference/bionic/

# ubuntu 18.04 has OpenFOAM 4.1 in the official repository

sudo: required
language: python
jobs:
  include:
    - os: linux
      dist: bionic
      python: 3.6
      env: TOXENV=FC_DAILY
  
    - os: linux
      dist: xenial
      python: 3.7
      env: TOXENV=FC_STABLE

# do not forget to do `# git update-index --chmod +x .travis/install.sh` and same for test.sh
install:
    - ./.travis/install.sh
script:
    - ./.travis/test.sh

# is that possible to install another software from another PPA?
# addons:
#   apt:
#     sources:
#     - ppa:freecad-maintainers/freecad-daily
#     #ppa:freecad-maintainers/freecad-stable
#     packages:
#       - freecad-daily
